### ISSUE TITLE
The mod just doesnt work.

### ISSUE THREAD

**Issue by justastranger101** [Temperz87/UK-Sound-Replacement#4]
Hello!
Ive followed the instructions, but the mod wont work (GUI WONT APPEAR IN THE ARCADE MACHINE)...
Ive seen that multiple people said that the mod doesnt work for them too.
If we are doing something wrong, can yall please make a tutorial that is directly aimed at this mod?

**Comment by Temperz87** [comment]
I'd like more information than "just doesn't work," and with the renewed interest in the mod I may end up making a tutorial for it. I'm just going to ask a bunch of questions so here goes:
1. Are you on the latest version of the Steam version of ULTRAKILL?
2. Are you on UMM version 0.5.0?
3. What other mods do you have loaded?
4. Is the mod loaded in UMM?
5. Can you provide your Player.log? This can be found by pressing the windows button + r then typing in "%appdata%\..\LocalLow\Hakita\ULTRAKILL\". You should see a file called Player.log, that's what I'm talking abuot.

**Comment by Temperz87** [comment]
I've also published a new release which fixes a bug, feel free to try that one.

**Comment by justastranger101** [comment]
ohh sorry... just realized that i needed UMM...

**Comment by Temperz87** [comment]
Welp I'm closing this issue, feel free to tell me if it doesn't work still.
